version: "3.8"

networks:
  backend:
    external: true
    name: minecraft-backend

services:
  # Minecraft Network Proxy Server
  # >> Moved to Stack mc-bungeecord/docker-compose.yml

  # Minecraft Survival Server
  # >> Moved to Stack mc-survival/docker-compose.yml

  # Minecraft Lobby, Creative, Minigames Server
  # >> Moved to Stack mc-main/docker-compose.yml

  # Nginx Proxy for Mod-support
  mc-mod-proxy:
    image: nginx
    container_name: mc_mod_proxy
    ports:
      - "24454:24454/udp" # Simple Voice Mod Port (Survival)
    networks:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # MySQL for Minecraft-Plugin-Use
  mc-mysql:
    image: mysql
    container_name: mc_mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: development-password-todo
      MYSQL_DATABASE: mc-btm
      MYSQL_USER: minecraft
      MYSQL_PASSWORD: development-minecraft-password-todo
    command: --default-authentication-plugin=mysql_native_password