version: '3'

#volumes:
#  bungeecord: {}

networks:
  #frontend:
    # add this if the network is already existing!
    #external: true
  backend:

services:

  # Minecraft Network Proxy Server
  mc-bungeecord:
    image: itzg/bungeecord
    container_name: mc_bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
      SPIGET_PLUGINS: "28140,241,1488,8695,9531,68956"
    ports:
      - "25565:25577"
    networks:
      - backend
    volumes:
      - ./mc-bungeecord:/server
      - ./mc-bungeecord/config.yml:/config/config.yml

  # Minecraft Lobby Server
  mc-lobby:
    image: itzg/minecraft-server
    container_name: mc_lobby
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      SPIGET_RESOURCES: "1997,390,6245,71465,63714,87226"
      plugins: "https://github.com/KosmX/emotes/releases/download/2.0.9/emotecraft-2.0.9-bukkit.jar,https://media.forgecdn.net/files/3543/517/voicechat-bukkit-1.18-2.1.16.jar"
      # Plugins:
      # - Emotecraft
      # - 93738 Simple Voice Chat
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./mc-lobby:/data
      - ./logs/lobby.log:/data/logs/latest.log

  # Minecraft Survival Server
  mc-survival:
    image: itzg/minecraft-server
    container_name: mc_survival
    environment:
      TYPE: "SPIGOT"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      SPIGET_RESOURCES: "1997,70616,7688,9089,1884,73997,34315,51856,16708,92546"
      plugins: "https://github.com/KosmX/emotes/releases/download/2.0.9/emotecraft-2.0.9-bukkit.jar,https://media.forgecdn.net/files/3543/517/voicechat-bukkit-1.18-2.1.16.jar"
      # Plugins:
      # - Emotecraft
      # - 93738 Simple Voice Chat
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./mc-survival:/data
      - ./logs/survival.log:/data/logs/latest.log

  # Minecraft Creative Server
  mc-creative:
    image: itzg/minecraft-server
    container_name: mc_creative
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      SPIGET_RESOURCES: "1997,70616,7688,390,25391,327"
      plugins: "https://github.com/KosmX/emotes/releases/download/2.0.9/emotecraft-2.0.9-bukkit.jar,https://media.forgecdn.net/files/3543/517/voicechat-bukkit-1.18-2.1.16.jar"
      # Plugins:
      # - Emotecraft
      # - 93738 Simple Voice Chat
      # Extern:
      # - 77506 PlotSquared: Premium Ressources require spiget-login, which is not documented for container-use
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./mc-creative:/data
      - ./logs/creative.log:/data/logs/latest.log

  # Minecraft Minigames Server
  mc-minigames:
    image: itzg/minecraft-server
    container_name: mc_minigames
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      SPIGET_RESOURCES: "1997,390,6245,63714,81702"
      plugins: "https://github.com/KosmX/emotes/releases/download/2.0.9/emotecraft-2.0.9-bukkit.jar,https://media.forgecdn.net/files/3543/517/voicechat-bukkit-1.18-2.1.16.jar"
      # Plugins:
      # - Emotecraft
      # - 93738 Simple Voice Chat
      # Extern:
      # - 45928 Quake: Premium Ressources require spiget-login, which is not documented for container-use
      # - 51321 AntiCooldown: Extern Site Download with Captcha
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./mc-minigames:/data
      - ./logs/minigames.log:/data/logs/latest.log

#  wordpress:
#
#  grafana:
