version: "3.8"

networks:
  backend:
    external: true
    name: minecraft-backend

services:
  # Minecraft Network Proxy Server
  mc-bungeecord:
    image: itzg/bungeecord
    hostname: mc-bungeecord
    env_file: .env
    ports:
      - "25565:25577"
    networks:
      - backend
    volumes:
      - ./mc-bungeecord:/server
      - ./mc-bungeecord/config.yml:/config/config.yml